// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZcvK6XCaKA40t9ukLYnGmmBzkFA0KB1w',
    appId: '1:1068522768332:web:47c704c6060af5d5e0bf69',
    messagingSenderId: '1068522768332',
    projectId: 'apars-classroom-ed36f',
    authDomain: 'apars-classroom-ed36f.firebaseapp.com',
    storageBucket: 'apars-classroom-ed36f.firebasestorage.app',
    measurementId: 'G-M9NNTZNS1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKV7sP07TnFEZSOPmgYXhoVRVjZ0vEoa0',
    appId: '1:1068522768332:android:f5981a498e45ceb0e0bf69',
    messagingSenderId: '1068522768332',
    projectId: 'apars-classroom-ed36f',
    storageBucket: 'apars-classroom-ed36f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfqfOgonQyoWl2eEPXFMnAt8oCfJQo68Q',
    appId: '1:1068522768332:ios:67e8085d155993fbe0bf69',
    messagingSenderId: '1068522768332',
    projectId: 'apars-classroom-ed36f',
    storageBucket: 'apars-classroom-ed36f.firebasestorage.app',
    iosBundleId: 'com.m360Assignment.app',
  );
}
